@startuml tables

entity "expenses" {
    *id
    --
    total_amount: float
    store_id <<FK>>
    store_name
    purchased_at: date
    note
}

entity "items" {
    *id
    --
    name
    price: float
    sub_category_id <<FK>>
    expense_id <<FK>>
}

entity "stores" {
    *id
    --
    name
}

entity "payment_methods" {
    *id
    --
    name
    color_id <<FK>>
    icon_id <<FK>>
}

entity "expenses_payment_methods" {
    *id
    --
    expense_id <<FK>>
    payment_method_id <<FK>>
    sub_total: float
}

entity "categories" {
    *id
    --
    name
}

entity "sub_categories" {
    *id
    --
    name
    tax_rate: float
    category_id <<FK>>
}

entity "colors" {
    *id
    --
    color_code
}

entity "icon_images" {
    *id
    --
    img_url
}

@enduml