@startuml
title 画面遷移図
left to right direction

note "画面1~5同士は画面下部のタブボタンで行き来できる（矢印は省略）" as note1

state "1. 支出一覧画面" as Expenses
Expenses : 支出一覧 / 支出詳細/編集画面へ
Expenses : +ボタン（登録用）（右上） / 支出登録画面へ
state "2. カテゴリごとの支出額画面" as Categories
Categories : カテゴリごとの支出額（月単位）、%表記付き
Categories : < / 前の月へ
Categories : > / 次の月へ
state "3. 決済方法ごとの支出額画面" as Payments
Payments : 決済方法ごとの支出額（月単位）、%表記付き
Payments : < / 前の月へ
Payments : > / 次の月へ
state "4. 店舗ごとの支出額画面" as Stores
Stores : 店舗ごとの支出額（月単位）、%表記付き
Stores : < / 前の月へ
Stores : > / 次の月へ
state "5. 設定画面" as Settings
Settings : カテゴリ一覧へのボタン / カテゴリ一覧へ
Settings : 決済方法一覧へのボタン / 決済方法一覧へ
Settings : よく行く店舗一覧へのボタン / よく行く店舗一覧へ

[*] --> Expenses : アプリ起動

state "6. 支出登録画面" as Expense_add
Expense_add : 決済方法、金額
Expense_add : 日付
Expense_add : 店舗
Expense_add : +ボタン（品物登録用）
Expense_add : 品物一覧（スワイプで削除、タップで編集）
Expense_add : Addボタン（右上） / 支出一覧画面へ
Expense_add : Cancel（左上） / 前の画面へ
state "7. 支出詳細/編集画面" as Expense_detail
Expense_detail : 決済方法、金額
Expense_detail : 日付
Expense_detail : 店舗
Expense_detail : +ボタン（品物登録用）
Expense_detail : 品物一覧（スワイプで削除、タップで編集）
Expense_detail : Saveボタン（右上） / 支出一覧画面へ
Expense_detail : Deleteボタン / 支出一覧画面へ
Expense_detail : Back（左上） / 前の画面へ
state "8. 決済方法選択ダイアログ" as Select_payment
Select_payment : 決済方法一覧
Select_payment : 金額入力欄（電卓キーボードで）
Select_payment : OK（右下） / ダイアログを閉じる
Select_payment : Cancel（左下） / ダイアログを閉じる
state "9. 日付選択ダイアログ" as Select_date
Select_date : カレンダー
Select_date : OK（右下） / ダイアログを閉じる
Select_date : Cancel（左下） / ダイアログを閉じる
state "10. 店舗選択ダイアログ" as Select_store
Select_store : 自由入力欄
Select_store : よく行く店舗一覧
Select_store : OK（右下） / ダイアログを閉じる
Select_store : Cancel（左下） / ダイアログを閉じる
state "11. 品物登録ダイアログ" as Add_item
Add_item : 金額入力欄（電卓キーボードで）
Add_item : カテゴリ選択プルダウン
Add_item : Add（右下） / ダイアログを閉じる
Add_item : Cancel（左下） / ダイアログを閉じる

Expenses --> Expense_add
Expenses --> Expense_detail

Expense_add --> Select_payment
Expense_add --> Select_date
Expense_add --> Select_store
Expense_add --> Add_item

Expense_detail --> Select_payment
Expense_detail --> Select_date
Expense_detail --> Select_store
Expense_detail --> Add_item

state "12. カテゴリごとの品物一覧画面" as Items_category
Items_category : 品物一覧
Items_category : Back（左上） / 前の画面へ

Categories --> Items_category

state "13. 店舗ごとの支出一覧画面" as Expenses_store
Expenses_store : 支出一覧
Expenses_store : Back（左上） / 前の画面へ

Stores --> Expenses_store
Expenses_store --> Expense_detail

state "14. カテゴリ一覧" as Category_list
Category_list : カテゴリ一覧（スワイプで削除） / カテゴリ編集ダイアログへ
Category_list : +ボタン（登録用）（右上） / カテゴリ登録ダイアログへ
Category_list : Back（左上） / 前の画面へ
state "15. カテゴリ登録ダイアログ" as Add_category
Add_category : 入力欄
Add_category : Add（右下） / ダイアログを閉じる
Add_category : Cancel（左下） / ダイアログを閉じる
state "16. カテゴリ編集ダイアログ" as Edit_category
Edit_category : 入力欄
Edit_category : Save（右下） / ダイアログを閉じる
Edit_category : Cancel（左下） / ダイアログを閉じる

state "17. 決済方法一覧" as Payment_list
Payment_list : 決済方法一覧（スワイプで削除） / 決済方法編集ダイアログへ
Payment_list : +ボタン（登録用）（右上） / 決済方法登録ダイアログへ
Payment_list : Back（左上） / 前の画面へ
state "18. 決済方法登録ダイアログ" as Add_payment
Add_payment : 入力欄
Add_payment : Add（右下） / ダイアログを閉じる
Add_payment : Cancel（左下） / ダイアログを閉じる
state "19. 決済方法編集ダイアログ" as Edit_payment
Edit_payment : 入力欄
Edit_payment : Save（右下） / ダイアログを閉じる
Edit_payment : Cancel（左下） / ダイアログを閉じる

state "20. よく行く店舗一覧" as Store_list
Store_list : よく行く店舗一覧（スワイプで削除） / よく行く店舗編集ダイアログへ
Store_list : +ボタン（登録用）（右上） / よく行く店舗登録ダイアログへ
Store_list : Back（左上） / 前の画面へ
state "21. よく行く店舗登録ダイアログ" as Add_store
Add_store : 入力欄
Add_store : Add（右下） / ダイアログを閉じる
Add_store : Cancel（左下） / ダイアログを閉じる
state "22. よく行く店舗編集ダイアログ" as Edit_store
Edit_store : 入力欄
Edit_store : Save（右下） / ダイアログを閉じる
Edit_store : Cancel（左下） / ダイアログを閉じる

Settings --> Category_list
Settings --> Payment_list
Settings --> Store_list
Category_list --> Add_category
Category_list --> Edit_category
Payment_list --> Add_payment
Payment_list --> Edit_payment
Store_list --> Add_store
Store_list --> Edit_store
@enduml
